table 'Measures Folder'
	lineageTag: bb07b7fc-739d-4025-ad63-44a53bc3ddf7

	measure 'Total Rides' = COUNTROWS(Trips)  --Counts all rows in the Trips table. Relies on upstream cleaning for invalid record removal.
		formatString: #,0
		displayFolder: Core
		lineageTag: 35679c21-9640-493e-b0ec-cda29b2a7a85

	measure 'Member Rides' =
			-- Filters to member rides only.
			CALCULATE(
			    COUNTROWS(Trips),
			    Trips[member_casual] = "member"
			)
		formatString: #,0
		displayFolder: Core
		lineageTag: 6db79f1f-c0f5-4f4d-b5a8-1233b46f9ad1

	measure 'Casual Rides' =
			-- Filters to casual rides only.
			CALCULATE(
			    COUNTROWS(Trips),
			    Trips[member_casual] = "casual"
			)
		formatString: #,0
		displayFolder: Core
		lineageTag: be6be4fd-a920-4032-b7fb-33a31ceb4691

	measure 'Member Ride %' =
			-- Returns the proportion of rides by members. BLANK() returned on divide-by-zero to stay consistent with null-handling convention.
			DIVIDE([Member Rides], [Total Rides], BLANK())
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Core
		lineageTag: 11101433-6c0f-461a-a7c7-f3c2f40514c9

	measure 'Avg Ride Duration (min)' =
			
			AVERAGEX(
			    FILTER(Trips, Trips[Ride Time (min)] > 0),
			    Trips[Ride Time (min)]
			)
			/*
			Averages decimal-minute ride durations. Filters out zero and blank values before averaging to avoid skewing the result.*/
		displayFolder: Core
		lineageTag: a2c0b2c2-3ef3-4e0b-8a20-d586c7707342

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Ride Distance (mi)' =
			
			/*Averages Haversine-calculated ride distances in miles. Same filter logic as duration.*/
			AVERAGEX(
			    FILTER(Trips, Trips[Ride Distance (mi)] > 0),
			    Trips[Ride Distance (mi)]
			)
		displayFolder: Core
		lineageTag: d1c15fe3-3deb-4e5d-952f-8063ec3bbdbc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Weekday Rides' = ```
			
			/*// Counts rides occurring on weekdays (Monday–Friday). Uses the Is Weekend column from the Date Table.*/
			CALCULATE([Total Rides], 'Date'[Is Weekend] = FALSE())
			
			
			```
		formatString: 0
		displayFolder: Temporal
		lineageTag: 39229bc2-e586-45ca-b573-b5e9184b63e1

	measure 'Weekend Rides' = ```
			
			/*Counts rides occurring on weekends (Saturday–Sunday).  */
			CALCULATE([Total Rides], 'Date'[Is Weekend] = TRUE())
			
			
			```
		formatString: 0
		displayFolder: Temporal
		lineageTag: 385add80-90d1-4541-a0f0-0092edc72052

	measure 'Weekend Ride %' = ```
			
			DIVIDE([Weekend Rides], [Total Rides], BLANK())
			/* 
			Proportion of all rides occurring on weekends. BLANK() returned on divide-by-zero consistent with null-handling convention. */
			```
		displayFolder: Temporal
		lineageTag: 89b49b6e-2e73-4d4d-b054-fef8a43cad66

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Duration Casual' = ```
			
			AVERAGEX(
			    FILTER(Trips, Trips[member_casual] = "casual" && Trips[Ride Time (min)] > 0),
			    Trips[Ride Time (min)]
			)
			/* 
			Average ride duration in decimal minutes for casual riders only. Same filter logic as member duration. */
			```
		displayFolder: Temporal
		lineageTag: 7e4ff32d-3ee1-42c8-adc3-8bbadc810dfc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Duration Member' = ```
			
			AVERAGEX(
			    FILTER(Trips, Trips[member_casual] = "member" && Trips[Ride Time (min)] > 0),
			    Trips[Ride Time (min)]
			)
			/* 
			Average ride duration in decimal minutes for members only. Filters out zero and blank values before averaging. */
			```
		displayFolder: Temporal
		lineageTag: 9aa5b069-a6d5-482e-b577-c6871963aecc

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Spring Rides' =
			
			CALCULATE([Total Rides], 'Date'[Season] = "Spring")
		formatString: 0
		displayFolder: Temporal
		lineageTag: f219d7ce-a056-4456-b38f-135d239ed2e0

	measure 'Summer Rides' =
			
			CALCULATE([Total Rides], 'Date'[Season] = "Summer")
		formatString: 0
		displayFolder: Temporal
		lineageTag: b5947c3c-179f-4a95-88c4-21896e4f11eb

	measure 'Fall Rides' =
			
			CALCULATE([Total Rides], 'Date'[Season] = "Fall")
		formatString: 0
		displayFolder: Temporal
		lineageTag: 6d3a04f8-3364-4453-8328-30e642eb177e

	measure 'Winter Rides' =
			
			CALCULATE([Total Rides], 'Date'[Season] = "Winter")
		formatString: 0
		displayFolder: Temporal
		lineageTag: 6c7f670e-3664-4518-9a74-f35c2973537a

	measure 'Casual Weekend %' = ```
			
			DIVIDE(
			    CALCULATE([Casual Rides], 'Date'[Is Weekend] = TRUE()),
			    [Casual Rides],
			    BLANK()
			)
			/* 
			Proportion of casual rides that occur on weekends. Expected to skew high — a key indicator that casual riders use the service recreationally rather than for commuting. */
			```
		displayFolder: Temporal
		lineageTag: 76988afe-4a8e-4edd-98db-0c3dfc5b7be2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Member Weekend %' = ```
			
			DIVIDE(
			    CALCULATE([Member Rides], 'Date'[Is Weekend] = TRUE()),
			    [Member Rides],
			    BLANK()
			)
			/* 
			Proportion of member rides that occur on weekends. Expected to be lower than casual weekend %, reflecting commuter usage patterns among members. */
			```
		displayFolder: Temporal
		lineageTag: 3602a300-1a7f-48bd-8db1-bbd1e0486aed

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Member Classic Rides' = ```
			
			CALCULATE([Member Rides], Trips[rideable_type] = "classic_bike")
			/* 
			Classic bike rides by members only. */
			```
		formatString: 0
		displayFolder: Bike Type
		lineageTag: b626a91d-e689-4f1f-9ca9-3c0408f9e2c6

	measure 'Classic Bike Rides' = ```
			
			CALCULATE([Total Rides], Trips[rideable_type] = "classic_bike")
			/* 
			Total rides on classic bikes across all rider types. */
			```
		formatString: 0
		displayFolder: Bike Type
		lineageTag: 4a557c83-6683-4610-b88b-736da32ef231

	measure 'Casual Classic Rides' = ```
			
			CALCULATE([Casual Rides], Trips[rideable_type] = "classic_bike")
			/* 
			Classic bike rides by casual riders only. */
			```
		formatString: 0
		displayFolder: Bike Type
		lineageTag: ebe69a27-a41a-49a7-b06e-61dfa6a0eeac

	measure 'Electric Bike Rides' = ```
			
			CALCULATE([Total Rides], Trips[rideable_type] = "electric_bike")
			/* 
			Total rides on electric bikes across all rider types. */
			```
		formatString: 0
		displayFolder: Bike Type
		lineageTag: 34fa55f0-e31b-4117-ad24-578bc89dc8ac

	measure 'Member Electric Rides' = ```
			
			CALCULATE([Member Rides], Trips[rideable_type] = "electric_bike")
			/* 
			Electric bike rides by members only. */
			```
		formatString: 0
		displayFolder: Bike Type
		lineageTag: cf453297-7318-4048-b05c-45ae00f8eaa0

	measure 'Casual Electric Rides' = ```
			
			CALCULATE([Casual Rides], Trips[rideable_type] = "electric_bike")
			/* 
			Electric bike rides by casual riders only. */
			```
		formatString: 0
		displayFolder: Bike Type
		lineageTag: 9d239f6a-dbeb-4ed8-ba8e-adbdf5337e61

	measure 'Docked Bike Rides' = ```
			
			CALCULATE([Total Rides], Trips[rideable_type] = "docked_bike")
			/* 
			Total rides on docked bikes. Returns BLANK() with current dataset — included for forward compatibility. */
			```
		formatString: 0
		displayFolder: Bike Type
		lineageTag: d64828e8-6b1f-4e0c-90df-e11550e9746d

	measure 'Member Docked Rides' = ```
			
			CALCULATE([Member Rides], Trips[rideable_type] = "docked_bike")
			/* 
			Docked bike rides by members only. Returns BLANK() with current dataset. */
			```
		formatString: 0
		displayFolder: Bike Type
		lineageTag: 65685e0d-534b-4722-adb0-ebfc96e6ce06

	measure 'Casual Docked Rides' = ```
			
			CALCULATE([Casual Rides], Trips[rideable_type] = "docked_bike")
			/* 
			Docked bike rides by casual riders only. Returns BLANK() with current dataset. */
			```
		formatString: 0
		displayFolder: Bike Type
		lineageTag: 06e0d7b1-746e-45a0-b546-55aad789af5a

	measure 'Classic Bike %' = ```
			
			DIVIDE([Classic Bike Rides], [Total Rides], BLANK())
			/* 
			Proportion of all rides on classic bikes. */
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Bike Type
		lineageTag: 5e6a8fd3-4c35-4257-a2de-8ccec3ac38b1

	measure 'Electric Bike %' = ```
			
			DIVIDE([Electric Bike Rides], [Total Rides], BLANK())
			/* 
			Proportion of all rides on electric bikes. */
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Bike Type
		lineageTag: 56db288f-28b8-469b-acdf-731e826cd547

	measure 'Docked Bike %' = ```
			
			DIVIDE([Docked Bike Rides], [Total Rides], BLANK())
			/* 
			Proportion of all rides on docked bikes. Returns BLANK() with current dataset. */
			```
		displayFolder: Bike Type
		lineageTag: c3fa7dcf-70b3-4d96-8419-10d7368986dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Rides with Start Station' = ```
			
			CALCULATE([Total Rides], Trips[start_station_name] <> BLANK())
			/* 
			Total rides where a start station name is recorded. */
			```
		formatString: 0
		displayFolder: Station
		lineageTag: 21e7ca21-121f-48ca-b2d9-e15237df4737

	measure 'Rides with End Station' = ```
			
			CALCULATE([Total Rides], Trips[end_station_name] <> BLANK())
			/* 
			Total rides where an end station name is recorded. */
			```
		formatString: 0
		displayFolder: Station
		lineageTag: ad76ce8e-37d6-48eb-9f5a-6a36864d561d

	measure 'Rides Missing Station Data' = ```
			
			[Total Rides] - [Rides with Start Station]
			/* 
			Quantifies rides with no start station recorded. Expected to be non-trivial, particularly for electric bike rides. */
			```
		formatString: 0
		displayFolder: Station
		lineageTag: fef9a94d-7fb0-493a-b7c4-bc9343524482

	measure 'Member Rides with Start Station' = ```
			
			CALCULATE([Member Rides], Trips[start_station_name] <> BLANK())
			/* 
			Member rides where a start station name is recorded. */
			```
		formatString: 0
		displayFolder: Station
		lineageTag: fb4627d7-7589-40ac-9e43-034eef53a013

	measure 'Casual Rides with Start Station' = ```
			
			CALCULATE([Casual Rides], Trips[start_station_name] <> BLANK())
			/* 
			Casual rides where a start station name is recorded. */
			```
		formatString: 0
		displayFolder: Station
		lineageTag: 8e89ca29-78f8-45bb-bce8-bc6d7ebb4ac1

	measure 'Round Trips' = ```
			
			CALCULATE(
			    [Total Rides],
			    Trips[start_station_name] = Trips[end_station_name]
			)
			/* 
			Total rides where the start and end station are the same. Indicator of recreational usage. */
			```
		formatString: 0
		displayFolder: Station
		lineageTag: 82f94991-72e7-456a-80cb-93b54ce49656

	measure 'Casual Round Trips' = ```
			
			CALCULATE(
			    [Casual Rides],
			    Trips[start_station_name] = Trips[end_station_name]
			)
			/* 
			Round trips by casual riders. Expected to be proportionally higher than members, consistent with recreational usage patterns. */
			```
		formatString: 0
		displayFolder: Station
		lineageTag: 00c5a554-c850-4710-ad94-249bc4e2e8a4

	measure 'Member Round Trips' = ```
			
			CALCULATE(
			    [Member Rides],
			    Trips[start_station_name] = Trips[end_station_name]
			)
			/* 
			Round trips by members. Expected to be proportionally lower, consistent with point-to-point commuter usage. */
			```
		formatString: 0
		displayFolder: Station
		lineageTag: f7a9d148-7109-4f87-9d43-e004da0a7af3

	measure 'Estimated Casual Revenue per Ride' =
			
			VAR AvgDuration = [Avg Duration Casual]
			VAR OverageMinutes = IF(AvgDuration > 30, AvgDuration - 30, 0)
			RETURN
			    3.30 + (OverageMinutes * 0.18)
		displayFolder: Revenue (Synthetic or Illustrative)
		lineageTag: 7f6fba28-35fb-4f2f-9f63-15dd464584aa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Estimated Casual Revenue' = ```
			
			SUMX(
			    FILTER(Trips, Trips[member_casual] = "casual" && Trips[Ride Time (min)] > 0),
			    VAR OverageMinutes = MAX(Trips[Ride Time (min)] - 30, 0)
			    RETURN 3.30 + (OverageMinutes * 0.18)
			)
			/* 
			Sums estimated casual revenue across all qualifying rides. Excludes rides with zero or blank duration. Overage calculated per ride before summing. */
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Revenue (Synthetic or Illustrative)
		lineageTag: e553028c-4a4d-4082-be3e-402ff65c1757

	measure 'Total Estimated Member Overage Revenue' = ```
			
			SUMX(
			    FILTER(Trips, Trips[member_casual] = "member" && Trips[Ride Time (min)] > 0),
			    VAR OverageMinutes = MAX(Trips[Ride Time (min)] - 45, 0)
			    RETURN OverageMinutes * 0.18
			)
			/* 
			Captures variable overage revenue from member rides exceeding the 45-minute included threshold at $0.18/min. Does not include the annual membership fee, which is not  amortized per ride in this model.*/
			```
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: Revenue (Synthetic or Illustrative)
		lineageTag: 7947a3bf-4f63-4c85-9ad7-67b5e38c7423

	measure 'Duration Ratio Casual to Member' =
			
			DIVIDE([Avg Duration Casual], [Avg Duration Member], BLANK())
			
			/* Ratio of average casual ride duration to average member ride duration. Values above 1 indicate casual riders take longer rides on average. Expected to be meaningfully above 1, consistent with recreational usage patterns. */
		displayFolder: Behavioral Ratios
		lineageTag: 8b01ceba-3b89-4a05-b55d-042f5a4448ca

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Distance Ratio Casual to Member' = ```
			
			DIVIDE([Avg Ride Distance Casual], [Avg Ride Distance Member], BLANK())
			/* 
			Ratio of average casual ride distance to average member ride distance. Compared alongside the duration ratio to assess whether casuals ride longer in time, distance, or both. */
			```
		displayFolder: Behavioral Ratios
		lineageTag: ae1cefb7-cec3-4337-97a4-d8984d1856eb

	measure 'Weekend Skew Ratio' = ```
			
			DIVIDE([Casual Weekend %], [Member Weekend %], BLANK())
			/* 
			How much more concentrated casual rides are on weekends relative to members. A value of 2 indicates casuals are twice as likely to ride on weekends compared to members. A key indicator of recreational vs. commuter usage patterns. */
			```
		displayFolder: Behavioral Ratios
		lineageTag: 67c71dc8-9d2d-4cc7-97ff-7d14fc8594f0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Round Trip Ratio Casual to Member' = ```
			
			DIVIDE(
			    DIVIDE([Casual Round Trips], [Casual Rides], BLANK()),
			    DIVIDE([Member Round Trips], [Member Rides], BLANK()),
			    BLANK()
			)
			/* 
			Compares the proportion of round trips for casual riders vs. members. Expected to be significantly above 1, supporting the conclusion that casual riders use the service recreationally while members use it for point-to-point commuting. */
			```
		displayFolder: Behavioral Ratios
		lineageTag: 3f64c7fe-2ce6-497f-8afb-6719fb65f822

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Ride Distance Member' = ```
			
			AVERAGEX(
			    FILTER(Trips, Trips[member_casual] = "member" && Trips[Ride Distance (mi)] > 0),
			    Trips[Ride Distance (mi)]
			)
			/* 
			Average ride distance in miles for members only. Filters out zero and blank values before averaging, consistent with other average measures in this project. Companion measure to Avg Ride Distance Casual — both are used to feed the Distance Ratio Casual to Member measure in Phase 5. */
			```
		displayFolder: Temporal
		lineageTag: f4e85ab1-5cbf-4f9b-8ac5-63c08aea31b7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg Ride Distance Casual' = ```
			
			AVERAGEX(
			    FILTER(Trips, Trips[member_casual] = "casual" && Trips[Ride Distance (mi)] > 0),
			    Trips[Ride Distance (mi)]
			)
			/* 
			Average ride distance in miles for casual riders only. Filters out zero and blank values before averaging, consistent with other average measures in this project. Companion measure to Avg Ride Distance Member — both are used to feed the Distance Ratio Casual to Member measure in Phase 5. */
			```
		displayFolder: Temporal
		lineageTag: 0f8e3835-efc6-4b03-8125-4c8acbaf957c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annotation Duration Ratio' =
			
			VAR Ratio = [Duration Ratio Casual to Member]
			RETURN
			    "Casual riders take rides " & FORMAT(Ratio, "0.00") & "x longer on average than members"
		isHidden
		displayFolder: Annotations
		lineageTag: 997763e5-a265-4d2f-8132-ac16b0961b17

		changedProperty = IsHidden

	measure 'Annotation Weekend Skew' =
			
			VAR Ratio = [Weekend Skew Ratio]
			RETURN
			    "Casual riders are " & FORMAT(Ratio, "0.00") & "x more likely to ride on weekends than members"
		isHidden
		displayFolder: Annotations
		lineageTag: 8efb37a5-ab00-4478-ac95-1db106be883b

		changedProperty = IsHidden

	measure 'Annotation Round Trip Ratio' =
			
			VAR Ratio = [Round Trip Ratio Casual to Member]
			RETURN
			    "Casual riders return to their starting station " & FORMAT(Ratio, "0.00") & "x more often than members"
		isHidden
		displayFolder: Annotations
		lineageTag: 0e6cddd6-d76b-4e03-a7af-05b4d0b995cb

		changedProperty = IsHidden

	measure 'Annotation Distance Ratio' =
			
			VAR Ratio = [Distance Ratio Casual to Member]
			RETURN
			    "Casual riders cover " & FORMAT(Ratio, "0.00") & "x the distance per ride compared to members"
		isHidden
		displayFolder: Annotations
		lineageTag: 58c5266b-31c3-4967-aa65-4063648d5d1b

		changedProperty = IsHidden

	measure 'Annotation Pace Insight' = ```
			
			VAR DurationRatio = [Duration Ratio Casual to Member]
			VAR DistanceRatio = [Distance Ratio Casual to Member]
			VAR DurationPct = FORMAT((DurationRatio - 1) * 100, "0") & "%"
			VAR DistancePct = FORMAT((DistanceRatio - 1) * 100, "0") & "%"
			RETURN
			    "Casual riders take " & DurationPct & " longer rides but cover only " & DistancePct & " more distance — suggesting a more leisurely pace than members. See the Ride Behavior page for more analysis."
			
			```
		isHidden
		displayFolder: Annotations
		lineageTag: cc3a21ca-f392-46be-84a0-71068744ab78

		changedProperty = IsHidden

	measure 'Round Trip % Member' = ```
			
			DIVIDE([Member Round Trips], [Member Rides], BLANK())
			/* 
			Proportion of member rides that are round trips. Used in Page 2 clustered bar chart for a fair comparison against casual round trip rate. */
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Behavioral Ratios
		lineageTag: b43b62a4-b4b9-4fb1-9c3e-16c36f6ffba3

	measure 'Round Trip % Casual' = ```
			
			DIVIDE([Casual Round Trips], [Casual Rides], BLANK())
			/* 
			Proportion of casual rides that are round trips. Used in Page 2 clustered bar chart for a fair comparison against member round trip rate. */
			```
		displayFolder: Behavioral Ratios
		lineageTag: 995f95eb-d03a-4521-bc3e-b84691653c35

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unit Duration' = "min"
		isHidden
		displayFolder: Annotations
		lineageTag: 42cc106f-e6e7-4bc0-98e3-0a369813d0e7

		changedProperty = IsHidden

	measure 'Unit Distance' = "mi"
		isHidden
		displayFolder: Annotations
		lineageTag: b9d28654-4e3e-4932-b9d8-89eb81579e60

		changedProperty = IsHidden

	measure 'Avg Duration Member Display' = ```
			
			FORMAT([Avg Duration Member], "0.0") & " min"
			/* 
			Text-formatted version of Avg Duration Member for use in the Page 2 duration card pair. Displays to one decimal place with "min" unit suffix. */
			```
		isHidden
		displayFolder: Annotations
		lineageTag: 9299aed3-c456-4144-a183-b2dafebee18a

		changedProperty = IsHidden

	measure 'Avg Duration Casual Display' = ```
			
			FORMAT([Avg Duration Casual], "0.0") & " min"
			/* 
			Text-formatted version of Avg Duration Casual for use in the Page 2 duration card pair. Displays to one decimal place with "min" unit suffix. */
			```
		isHidden
		displayFolder: Annotations
		lineageTag: e459aa4e-35cd-421d-aa1f-6dd4d29b6f59

		changedProperty = IsHidden

	measure 'Avg Ride Distance Member Display' = ```
			
			FORMAT([Avg Ride Distance Member], "0.00") & " mi"
			/* 
			Text-formatted version of Avg Ride Distance Member for use in the Page 2 distance card pair. Displays to two decimal places with "mi" unit suffix. */
			```
		isHidden
		displayFolder: Annotations
		lineageTag: 6d8e292f-1d9e-4c43-95d3-3b90b5f158c9

		changedProperty = IsHidden

	measure 'Avg Ride Distance Casual Display' = ```
			
			FORMAT([Avg Ride Distance Casual], "0.00") & " mi"
			/* 
			Text-formatted version of Avg Ride Distance Casual for use in the Page 2 distance card pair. Displays to two decimal places with "mi" unit suffix. */
			```
		isHidden
		displayFolder: Annotations
		lineageTag: 43cbbecb-1db8-4540-8bfc-4b9bc2fd00ad

		changedProperty = IsHidden

	measure 'Member % by Metric' =
			
			SWITCH(
			    SELECTEDVALUE('Metric Groups'[Metric]),
			    "Weekend %", [Member Weekend %],
			    "Round Trip %", [Round Trip % Member],
			    BLANK()
			)
			/* Returns the appropriate member percentage measure based on the selected metric category from the Metric Groups table. Used as a Y-axis series in the Page 2 clustered column chart. Set color to #1F77B4 in the visual format pane. */
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Behavioral Ratios
		lineageTag: 3421be5d-e7f7-4dd4-b030-91bf5d6fefd7

	measure 'Casual % by Metric' = ```
			
			SWITCH(
			    SELECTEDVALUE('Metric Groups'[Metric]),
			    "Weekend %", [Casual Weekend %],
			    "Round Trip %", [Round Trip % Casual],
			    BLANK()
			)
			/* 
			Returns the appropriate casual percentage measure based on the selected metric category from the Metric Groups table. Used as a Y-axis series in the Page 2 clustered column chart. Set color to #FF7F0E in the visual format pane. */
			```
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Behavioral Ratios
		lineageTag: 4e67ee63-c34e-452d-8436-4b30165c78df

	measure 'Annotation Page 2 Pace Insight' =
			
			VAR DurationRatio = [Duration Ratio Casual to Member]
			VAR DistanceRatio = [Distance Ratio Casual to Member]
			VAR DurationPct = FORMAT((DurationRatio - 1) * 100, "0")
			VAR DistancePct = FORMAT(ABS(DistanceRatio - 1) * 100, "0")
			VAR DistanceDirection = IF(DistanceRatio >= 1, "more", "less")
			RETURN
			    "Casual riders take " & DurationPct & "% longer rides but cover only " & DistancePct & "% " & DistanceDirection & " distance than members. This suggests casual riders move at a more leisurely pace — prioritizing the experience of riding over reaching a destination efficiently."
		displayFolder: Annotations
		lineageTag: cddb6663-e08b-41a5-8be6-92ff5b79da4e

	measure 'Annotation Duration Card Callout' = ```
			
			VAR DurationRatio = [Duration Ratio Casual to Member]
			VAR DurationPct = FORMAT((DurationRatio - 1) * 100, "0")
			RETURN
			    "Casual riders average " & DurationPct & "% longer rides than members"
			/* 
			Dynamic text callout displayed beneath the duration card pair on Page 2. Updates automatically when slicers are adjusted.
			 */
			```
		displayFolder: Annotations
		lineageTag: 73577803-7433-4f1e-a5b6-38536db0fb47

	measure 'Annotation Distance Card Callout' = ```
			
			VAR DistanceRatio = [Distance Ratio Casual to Member]
			VAR DistancePct = FORMAT((DistanceRatio - 1) * 100, "0")
			RETURN
			    IF(
			        DistanceRatio >= 1,
			        "Casual riders cover " & DistancePct & "% more distance per ride than members",
			        "Casual riders cover " & FORMAT((1 - DistanceRatio) * 100, "0") & "% less distance per ride than members"
			    )
			/* 
			Dynamic text callout displayed beneath the distance card pair on Page 2. Handles both directions — if casual riders cover more distance it says "more", if less it says "less". Updates automatically when slicers are adjusted. */
			```
		displayFolder: Annotations
		lineageTag: 0300ed63-7254-4f84-8df6-d7daad5f0401

	measure 'Member Rides by Day Type' = ```
			
			SWITCH(
			    SELECTEDVALUE('Day Type Groups'[Day Type]),
			    "Weekday", CALCULATE([Member Rides], 'Date'[Is Weekend] = FALSE()),
			    "Weekend", CALCULATE([Member Rides], 'Date'[Is Weekend] = TRUE()),
			    BLANK()
			)
			/* 
			Returns member ride count for the selected day type category from the Day Type Groups table. Used as a Y-axis series in the Page 3 Weekday vs Weekend clustered column chart. */
			```
		formatString: 0
		displayFolder: Temporal
		lineageTag: dc759f39-51d3-46c0-8eb1-e21330f79f1d

	measure 'Casual Rides by Day Type' = ```
			
			SWITCH(
			    SELECTEDVALUE('Day Type Groups'[Day Type]),
			    "Weekday", CALCULATE([Casual Rides], 'Date'[Is Weekend] = FALSE()),
			    "Weekend", CALCULATE([Casual Rides], 'Date'[Is Weekend] = TRUE()),
			    BLANK()
			)
			/* 
			Returns casual ride count for the selected day type category from the Day Type Groups table. Used as a Y-axis series in the Page 3 Weekday vs Weekend clustered column chart */
			```
		formatString: 0
		displayFolder: Temporal
		lineageTag: 3c5e4e47-13e5-4eff-bce2-822e41427762

	measure 'Annotation Page 3 Temporal Insight' =
			
			VAR SummerCasual = [Summer Rides] - CALCULATE([Summer Rides], Trips[member_casual] = "member")
			VAR TotalCasual = [Casual Rides]
			VAR SummerCasualPct = FORMAT(DIVIDE(SummerCasual, TotalCasual) * 100, "0")
			RETURN
			    "Members spike at commuter hours and favor weekdays year-round. Casual riders peak midday and on weekends — with " & SummerCasualPct & "% of all casual rides occurring in summer months."
		displayFolder: Annotations
		lineageTag: d85a3556-f97f-4349-a95f-0732c283e2b9

	partition 'Measures Folder' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

